### ISSUE TITLE
There is no command to run the app on a localhost server

### ISSUE THREAD

**Issue by asingh04** [hstevanoski/redux-notes-app#1]
The given command `npm run dev` just starts the webpack on `watch` mode to see any file is changed and rebuild the app, it doesn't start a localhost server. Can you add a script for it or should I make PR?

**Comment by hstevanoski** [comment]
This is a good suggestion. However, the idea behind this project is to explain the very fundamentals of Redux. That's why I'm trying to keep the project as simple as possible.
Further, there are a lot of people who have read the article but don't have such advanced knowledge and\or are somewhat beginners. I wouldn't want to get them confused with concepts that are outside of the scope of the article or the idea behind this project, for that matter.
Thank you for your suggestion!
